export const data = [
  {
    id: "123",
    commodity: "",
    img: "",
    status: "",
    category: "",
    shippedFrom: "",
    shippedTo: "",
    deliveryTrackingNumber: "",
    valueOfOrder: "",
    supplier: "",
    orderValue: "",
    expiryDate: "",
    targetSellingDate: "",
    productCertification: "",
    managementSystem: "",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    PO: "",
    arrivingToday: false,
  },
  {
    id: "2",
    commodity: "",
    img: "",
    status: "",
    category: "",
    shippedFrom: "",
    shippedTo: "",
    deliveryTrackingNumber: "",
    valueOfOrder: "",
    supplier: "",
    orderValue: "",
    expiryDate: "",
    targetSellingDate: "",
    productCertification: "",
    managementSystem: "",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    PO: "",
    arrivingToday: false,
  },
  {
    id: "3",
    commodity: "potatoes",
    img: "",
    status: "",
    category: "",
    shippedFrom: "",
    shippedTo: "",
    deliveryTrackingNumber: "",
    valueOfOrder: "",
    supplier: "",
    orderValue: "",
    expiryDate: "",
    targetSellingDate: "",
    productCertification: "",
    managementSystem: "",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    PO: "",
    arrivingToday: true,
  },
];
