export const data = [
  {
    id: "123",
    commodity: "potatoes",
    img:
      "https://assets.bonappetit.com/photos/5d7284758d926f0009df5cfc/5:4/w_3165,h_2532,c_limit/Basically-Gojuchang-Chicken-Potato.jpg",
    status: "",
    category: "",
    shippedFrom: "Lombardy, Italy",
    shippedTo: "Paris, France",
    deliveryTrackingNumber: "1021453654",
    valueOfOrder: "£9,0000",
    volume: "100 tonnes",
    supplier: "Grechen Corp.ltd",

    expiryDate: "18/11/20",
    targetSellingDate: "16/11/20",
    productCertification: "Organic",
    managementSystem: "IS9001",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    po: "121334563",
    arrivingToday: true,
  },
  {
    id: "2",
    commodity: "Onions",
    img: "",
    status: "",
    category: "",
    shippedFrom: "Lombardy, Italy",
    shippedTo: "Paris, France",
    deliveryTrackingNumber: "1021453654",
    valueOfOrder: "£9,0000",
    volume: "100 tonnes",
    supplier: "Grechen Corp.ltd",
    expiryDate: "18/11/20",
    targetSellingDate: "16/11/20",
    productCertification: "Organic",
    managementSystem: "IS9001",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    po: "4547525456",
    arrivingToday: false,
  },
  {
    id: "3",
    commodity: "Carrots",
    img: "",
    status: "",
    category: "",
    shippedFrom: "Lombardy, Italy",
    shippedTo: "Paris, France",
    deliveryTrackingNumber: "1021453654",
    valueOfOrder: "£9,0000",
    volume: "100 tonnes",
    supplier: "Grechen Corp.ltd",
    expiryDate: "18/11/20",
    targetSellingDate: "16/11/20",
    productCertification: "Organic",
    managementSystem: "IS9001",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    po: "2547896541",
    arrivingToday: false,
  },
];
