export const data = [
  {
    id: "123",
    commodity: "potatoes",
    img: "",
    status: "",
    category: "",
    shippedFrom: "Lombardy, Italy",
    shippedTo: "Paris, France",
    deliveryTrackingNumber: "1021453654",
    valueOfOrder: "£9,0000",
    volume: "100 tonnes",
    supplier: "Grechen Corp.ltd",

    expiryDate: "18/11/20",
    targetSellingDate: "16/11/20",
    productCertification: "Organic",
    managementSystem: "IS9001",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    PO: "",
    arrivingToday: true,
  },
  {
    id: "2",
    commodity: "Onions",
    img: "",
    status: "",
    category: "",
    shippedFrom: "Lombardy, Italy",
    shippedTo: "Paris, France",
    deliveryTrackingNumber: "1021453654",
    valueOfOrder: "£9,0000",
    volume: "100 tonnes",
    supplier: "Grechen Corp.ltd",

    expiryDate: "18/11/20",
    targetSellingDate: "16/11/20",
    productCertification: "Organic",
    managementSystem: "IS9001",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    PO: "",
    arrivingToday: false,
  },
  {
    id: "3",
    commodity: "Carrots",
    img: "",
    status: "",
    category: "",
    shippedFrom: "Lombardy, Italy",
    shippedTo: "Paris, France",
    deliveryTrackingNumber: "1021453654",
    valueOfOrder: "£9,0000",
    volume: "100 tonnes",
    supplier: "Grechen Corp.ltd",

    expiryDate: "18/11/20",
    targetSellingDate: "16/11/20",
    productCertification: "Organic",
    managementSystem: "IS9001",
    onTimeDeliveryStatus: true,
    quality: [],
    validationStatus: true,
    PO: "",
    arrivingToday: false,
  },
];
